### ISSUE TITLE
Allow JsonString type to be renamed

### ISSUE THREAD

**Issue by sb8244** [ash-project/ash_graphql#151]
**Is your feature request related to a problem? Please describe.**

I am bringing Ash into an existing GraphQL schema. This schema defines JsonString (based on the Absinthe suggested type, I think) and the definition is different from how Ash does it.

**Describe the solution you'd like**

I'd like to be able to give a different name than `JsonString` so that I do not have a name collision in my types

**Describe alternatives you've considered**

* I could remove my old definition of JsonString and use Ash's. I would need to implement this across my existing codebase.
* I could implement a new Schema and expose a different endpoint for the Ash layer

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

N/A

**Additional context**
Slack link: https://elixir-lang.slack.com/archives/C0193AHFLPN/p1715449075213649?thread_ts=1715445271.473749&cid=C0193AHFLPN

**Comment by zachdaniel** [comment]
So we did some investigation and determined that issue lies in the way that we import those types, and that the desire would be for it to be done conditionally. I've made that change here: 761a60f3b4a548ac48c93e480c80aa1fe6c7d5d7

It's not documented yet because it is still experimental. @sb8244 you can use it with `use AshGraphql, auto_import_absinthe_types?: false`

Please reopen this issue if that doesn't work 🙇

**Comment by sb8244** [comment]
This worked great for me

```
  use AshGraphql, domains: [Super.BackroomAsh], auto_import_absinthe_types?: false

  # Manually include Ash types
  import_types(Absinthe.Type.Custom)
  import_types(AshGraphql.Types.JSON)
```

Thanks a ton!
