### ISSUE TITLE
Feature: Add `has_all` filter for arrays/lists

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash_graphql#18]
**Is your feature request related to a problem? Please describe.**
Given the type `attribute(:roles, {:array, :atom}`, it is possible but clunky to use `has` and boolean logic with `and` to filter on where the `roles` field contains all items in a given list.

**Describe the solution you'd like**
I would like a filter function akin to `roles has all items in [opts]` that would handle that logic.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example:

```graphql
filter: { roles: { has_all: [OPTION1, OPTION2, ...] } }
```

**Comment by zachdaniel** [comment]
I've labeled this "good first issue" although it is middle-to-advanced. THe reason its a good first issue, though, is because ultimately this adds a new operator to the filter syntax (and so should be done in ash core), but that operator simply should return (at least to start) a new boolean expression that is `roles has OPTION1 and roles has OPTION2`. So it should be reasonably isolated.

**Comment by zachdaniel** [comment]
Anyone will be able to add this kind of thing when we do custom operators/functions.
